"""Repeating-key XOR rendered as binary octets."""

from __future__ import annotations


def binary_xor_text_encrypt(plaintext: str, key: str) -> str:
    """Encrypt text and return space-separated 8-bit binary values."""
    if not key:
        raise ValueError("key must not be empty")
    data = plaintext.encode("utf-8")
    key_bytes = key.encode("utf-8")
    xored = [byte ^ key_bytes[i % len(key_bytes)] for i, byte in enumerate(data)]
    return " ".join(f"{value:08b}" for value in xored)


def binary_xor_text_decrypt(ciphertext: str, key: str) -> str:
    """Decrypt text generated by :func:`binary_xor_text_encrypt`."""
    if not key:
        raise ValueError("key must not be empty")
    parts = [p for p in ciphertext.split() if p]
    data = bytes(int(part, 2) for part in parts)
    key_bytes = key.encode("utf-8")
    plain = bytes(byte ^ key_bytes[i % len(key_bytes)] for i, byte in enumerate(data))
    return plain.decode("utf-8")
