"""Repeating-key XOR encoded as octal bytes."""

from __future__ import annotations


def octal_xor_encrypt(plaintext: str, key: str) -> str:
    """Encrypt text with repeating-key XOR and return space-separated octal bytes."""
    if not key:
        raise ValueError("key must not be empty")
    data = plaintext.encode("utf-8")
    key_bytes = key.encode("utf-8")
    xored = [byte ^ key_bytes[i % len(key_bytes)] for i, byte in enumerate(data)]
    return " ".join(f"{value:03o}" for value in xored)


def octal_xor_decrypt(ciphertext: str, key: str) -> str:
    """Decrypt text generated by :func:`octal_xor_encrypt`."""
    if not key:
        raise ValueError("key must not be empty")
    parts = [p for p in ciphertext.split() if p]
    data = bytes(int(part, 8) for part in parts)
    key_bytes = key.encode("utf-8")
    plain = bytes(byte ^ key_bytes[i % len(key_bytes)] for i, byte in enumerate(data))
    return plain.decode("utf-8")
